### ISSUE TITLE
Update to akka v1.3+

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Akka.Persistence.Cassandra#38]
This plugin probably needs to be updated. AFAIK there were a lot of changes since 1.0.+ regarding persistence layer.

**Comment by Horusiath** [comment]
The related details about issues have been described here: https://github.com/Horusiath/Akkling/issues/95

**Comment by HIPERCUBE** [comment]
It's not works on 1.3.9 version(akka).

```
[ERROR][11/14/2018 11:53:05][Thread 0027][akka://ActorSystem/system/sharding/Coordinator/singleton/coordinator] Method 'ReplayMessagesAsync' in type 'Akka.Persistence.Cassandra.Journal.CassandraJournal' from assembly 'Akka.Persistence.Cassandra, Version=1.0.6.3, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Cause: [akka://ActorSystem/system/sharding/Coordinator/singleton/coordinator#1346149396]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Method 'ReplayMessagesAsync' in type 'Akka.Persistence.Cassandra.Journal.CassandraJournal' from assembly 'Akka.Persistence.Cassandra, Version=1.0.6.3, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Akka.Persistence.PersistenceExtension.CreatePlugin(ExtendedActorSystem system, String configPath, Config pluginConfig)
   at Akka.Persistence.PersistenceExtension.NewPluginHolder(ExtendedActorSystem system, String configPath, String fallbackPath)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Akka.Persistence.PersistenceExtension.PluginHolderFor(String configPath, String fallbackPath)
   at Akka.Persistence.PersistenceExtension.JournalFor(String journalPluginId)
   at Akka.Persistence.Eventsourced.get_Journal()
   at Akka.Persistence.Eventsourced.AroundPreStart()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

**Comment by HIPERCUBE** [comment]
@Aaronontheweb Do you have any plans to support akka 1.3+ version?
